# yaml-language-server: $schema=https://json.schemastore.org/golangci-lint.json
linters-settings:
  custom:
    refdir:
      type: module
      description: "Report potential reference-to-decleration ordering issues"
      original-url: "github.com/devnev/refdir"
      # All settings are optional.
      # These example settings correspond to the analyzer defaults.
      # Possible values are 'up', 'down', and 'ignore'
      settings:
        directions:
          func: down
          type: down
          recvtype: up
          var: down
          const: down

linters:
  disable-all: true
  enable:
    - refdir
