# yaml-language-server: $schema=https://json.schemastore.org/golangci-lint.json
linters-settings:
  custom:
    refdir:
      type: module
      description: "Report potential reference-to-decleration ordering issues"
      original-url: "github.com/devnev/refdir"

linters:
  disable-all: true
  enable:
    - refdir
