linters-settings:
  custom:
    refdir:
      type: module
      description: "Report potential reference-to-decleration ordering issues",
      original-url: "github.com/devnev/refdir"
      settings: {}

linters:
  disable-all: true
  enable:
    - refdir
